### ISSUE TITLE
SprotoCodec 解码的一个 bug

### ISSUE THREAD

**Issue by yzbyzz** [sundream/mysproto#1]
## 现象
你提供的测试样例中有 “SprotoObject 中有一个 SprotoObject List” 的情况，可以正常编解码；没有这种 “SprotoObject 中有一个 SprotoObject” 的情况，刚好这种情况有个小问题。

用如下的代码进行测试，在解码时会报错：
```
                      string proto = @"
				.Message {
					id 0 : integer
				}
				.Package {
					id 0 : integer
					message 1 : Message
				}
			";
			SprotoMgr sprotoMgr = SprotoParser.Parse(proto);
			
			SprotoObject message = sprotoMgr.NewSprotoObject("Message");
			message["id"] = 1234;
			
			SprotoObject package = sprotoMgr.NewSprotoObject("Package");
			package["id"] = 5678;
			package["message"] = message;
			
			package.Dump();
			
			
			SprotoStream encode = sprotoMgr.Encode(package);
			
			SprotoStream decode = encode;
			decode.Seek(0, SprotoStream.SEEK_BEGIN);
			
			SprotoObject decodePackage = sprotoMgr.Decode("Package", decode);
			decodePackage.Dump();
```

## 解决
在 
https://github.com/sundream/mysproto/blob/79d3dc8335043602283d4bdacb0d207e45732c04/SprotoCodec.cs#L195
之前加一句 `UInt32 dataLen = this.ReadUInt32(reader);` 来读取 SprotoObject 的长度即可。

**Comment by sundream** [comment]
非常抱歉，这个项目因为没多少人用，没怎么维护，最近1个月我已经用于自己的项目，优化了部分API，以及一些bug，这周应该会更新下，你这个问题我已经处理好

**Comment by sundream** [comment]
最新代码 已经提交，你可以review看下

**Comment by yzbyzz** [comment]
我看了， f9f5b0cbbc816a58ae56367529fb089d029f7c33  这次提交已经解决了这个问题。
